[project]
name = "sakura-contracts"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[repl.analysis]
passes = []
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts.sakura-market-v5]
path = "contracts/sakura-market-v5.clar"
clarity_version = 3
epoch = "3.1"

[repl.settings]
include_boot_contracts = ["pox-4", "costs-3", "cost-voting"]